# Generated by Django 2.1.1 on 2018-09-15 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(blank=models.TextField(), default=datetime.datetime(2018, 9, 16, 1, 18, 29, 315568)),
        ),
    ]
